version: '2.3'
services:
  test-cpu-base:
    build:
      context: .
      dockerfile: Dockerfile.test.cpu
      args:
        UBUNTU_VERSION: 18.04
        GPP_VERSION: 7
        MPI_KIND: None
        PYTHON_VERSION: 3.6
        TENSORFLOW_PACKAGE: tensorflow-cpu==2.4.1
        KERAS_PACKAGE: keras==2.4.3
        PYTORCH_PACKAGE: torch==1.7.1+cpu
        TORCHVISION_PACKAGE: torchvision==0.4.0+cpu
        MXNET_PACKAGE: mxnet==1.7.0.post1
        PYSPARK_PACKAGE: pyspark==3.0.1
        SPARK_PACKAGE: spark-3.0.1/spark-3.0.1-bin-hadoop2.7.tgz
    privileged: true
    shm_size: 8gb

  test-cpu-mpich-py3_6-tf2_4_1-keras2_4_3-torch1_7_1-mxnet1_7_0_p1-pyspark_3_0_1:
    extends: test-cpu-base
    build:
      args:
        MPI_KIND: MPICH
  test-cpu-oneccl-ofi-py3_6-tf2_4_1-keras2_4_3-torch1_7_1-mxnet1_7_0_p1-pyspark_3_0_1:
    extends: test-cpu-base
    build:
      args:
        MPI_KIND: ONECCL
  test-cpu-oneccl-py3_6-tf2_4_1-keras2_4_3-torch1_7_1-mxnet1_7_0_p1-pyspark_3_0_1:
    extends: test-cpu-base
    build:
      args:
        MPI_KIND: ONECCL
  test-cpu-openmpi-py3_6-tf2_4_1-keras2_4_3-torch1_7_1-mxnet1_7_0_p1-pyspark_3_0_1:
    extends: test-cpu-base
    build:
      args:
        MPI_KIND: OpenMPI
  test-cpu-openmpi-gloo-py3_6-tf2_4_1-keras2_4_3-torch1_7_1-mxnet1_7_0_p1-pyspark_3_0_1:
    extends: test-cpu-base
    build:
      args:
        MPI_KIND: OpenMPI

  test-cpu-gloo-py3_6-tf1_15_5-keras2_2_4-torch1_2_0-mxnet1_4_1-pyspark_3_0_1:
    extends: test-cpu-base
    build:
      args:
        TENSORFLOW_PACKAGE: tensorflow-cpu==1.15.5
        KERAS_PACKAGE: keras==2.2.4
        PYTORCH_PACKAGE: torch==1.2.0+cpu
        TORCHVISION_PACKAGE: torchvision==0.4.0+cpu
        MXNET_PACKAGE: mxnet==1.4.1
  test-cpu-gloo-py3_6-tf2_0_4-keras2_3_1-torch1_3_1-mxnet1_4_1-pyspark_3_0_1:
    extends: test-cpu-base
    build:
      args:
        TENSORFLOW_PACKAGE: tensorflow-cpu==2.0.4
        KERAS_PACKAGE: keras==2.3.1
        PYTORCH_PACKAGE: torch==1.3.1+cpu
        TORCHVISION_PACKAGE: torchvision==0.4.0+cpu
        MXNET_PACKAGE: mxnet==1.4.1
  test-cpu-gloo-py3_6-tf2_1_3-keras2_3_1-torch1_4_0-mxnet1_5_1-pyspark_3_0_1:
    extends: test-cpu-base
    build:
      args:
        TENSORFLOW_PACKAGE: tensorflow-cpu==2.1.3
        KERAS_PACKAGE: keras==2.3.1
        PYTORCH_PACKAGE: torch==1.4.0+cpu
        TORCHVISION_PACKAGE: torchvision==0.4.0+cpu
        MXNET_PACKAGE: mxnet==1.5.1
  test-cpu-gloo-py3_6-tf2_2_2-keras2_3_1-torch1_5_1-mxnet1_6_0-pyspark_3_0_1:
    extends: test-cpu-base
    build:
      args:
        TENSORFLOW_PACKAGE: tensorflow-cpu==2.2.2
        KERAS_PACKAGE: keras==2.3.1
        PYTORCH_PACKAGE: torch==1.5.1+cpu
        TORCHVISION_PACKAGE: torchvision==0.4.0+cpu
        MXNET_PACKAGE: mxnet==1.6.0
  test-cpu-gloo-py3_6-tf2_3_2-keras2_3_1-torch1_6_0-mxnet1_7_0_p1-pyspark_3_0_1:
    extends: test-cpu-base
    build:
      args:
        TENSORFLOW_PACKAGE: tensorflow-cpu==2.3.2
        KERAS_PACKAGE: keras==2.3.1
        PYTORCH_PACKAGE: torch==1.6.0+cpu
        TORCHVISION_PACKAGE: torchvision==0.4.0+cpu
        MXNET_PACKAGE: mxnet==1.7.0.post1
  test-cpu-gloo-py3_6-tf2_4_1-keras2_4_3-torch1_7_1-mxnet1_7_0_p1-pyspark_3_0_1:
    extends: test-cpu-base
    build:
      args:
        TENSORFLOW_PACKAGE: tensorflow-cpu==2.4.1
        KERAS_PACKAGE: keras==2.4.3
        PYTORCH_PACKAGE: torch==1.7.1+cpu
        TORCHVISION_PACKAGE: torchvision==0.4.0+cpu
        MXNET_PACKAGE: mxnet==1.7.0.post1
  test-cpu-gloo-py3_6-tfhead-keras2_4_3-torchhead-mxnethead-pyspark_3_0_1:
    extends: test-cpu-base
    build:
      args:
        TENSORFLOW_PACKAGE: tf-nightly
        KERAS_PACKAGE: keras==2.4.3
        PYTORCH_PACKAGE: torch-nightly
        TORCHVISION_PACKAGE: torchvision
        MXNET_PACKAGE: mxnet-nightly

  test-cpu-gloo-py3_6-tf2_4_1-keras2_4_3-torch1_7_1-mxnet1_7_0_p1-pyspark_2_3_4:
    extends: test-cpu-base
    build:
      args:
        PYTHON_VERSION: 3.6
        PYSPARK_PACKAGE: pyspark==2.3.4
        SPARK_PACKAGE: spark-2.3.4/spark-2.3.4-bin-hadoop2.7.tgz
  test-cpu-gloo-py3_7-tf2_4_1-keras2_4_3-torch1_7_1-mxnet1_7_0_p1-pyspark_2_4_7:
    extends: test-cpu-base
    build:
      args:
        PYTHON_VERSION: 3.7
        PYSPARK_PACKAGE: pyspark==2.4.7
        SPARK_PACKAGE: spark-2.4.7/spark-2.4.7-bin-hadoop2.7.tgz
  test-cpu-gloo-py3_8-tf2_4_1-keras2_4_3-torch1_7_1-mxnet1_7_0_p1-pyspark_3_0_1:
    extends: test-cpu-base
    build:
      args:
        PYTHON_VERSION: 3.8
        PYSPARK_PACKAGE: pyspark==3.0.1
        SPARK_PACKAGE: spark-3.0.1/spark-3.0.1-bin-hadoop2.7.tgz

  test-gpu-base:
    build:
      context: .
      dockerfile: Dockerfile.test.gpu
      args:
        GPP_VERSION: 7
        MPI_KIND: None
        PYTHON_VERSION: 3.6
        TENSORFLOW_PACKAGE: tensorflow-cpu==2.4.1
        KERAS_PACKAGE: keras==2.4.3
        PYTORCH_PACKAGE: torch==1.7.1+cpu
        TORCHVISION_PACKAGE: torchvision==0.4.0+cpu
        MXNET_PACKAGE: mxnet==1.7.0.post1
        PYSPARK_PACKAGE: pyspark==3.0.1
        SPARK_PACKAGE: spark-3.0.1/spark-3.0.1-bin-hadoop2.7.tgz
    runtime: nvidia
    # We plumb CUDA_VISIBLE_DEVICES instead of NVIDIA_VISIBLE_DEVICES because
    # the latter does not work in privileged mode that we use in the containers.
    environment:
      - CUDA_VISIBLE_DEVICES
    privileged: true
    shm_size: 8gb

  test-gpu-gloo-py3_6-tf1_15_5-keras2_2_4-torch1_2_0-mxnet1_4_1-pyspark_3_0_1:
    extends: test-gpu-base
    build:
      args:
        CUDA_DOCKER_VERSION: 10.0-devel-ubuntu18.04
        TENSORFLOW_PACKAGE: tensorflow-gpu==1.15.0
        KERAS_PACKAGE: keras==2.2.4
        PYTORCH_PACKAGE: torch==1.2.0+cu100
        TORCHVISION_PACKAGE: torchvision==0.4.1+cu100
        MXNET_PACKAGE: mxnet-cu100==1.4.1
  test-gpu-gloo-py3_6-tf2_3_2-keras2_3_1-torch1_6_0-mxnet1_7_0_p1-pyspark_3_0_1:
    extends: test-gpu-base
    build:
      args:
        CUDA_DOCKER_VERSION: 10.1-devel-ubuntu18.04
        TENSORFLOW_PACKAGE: tensorflow-gpu==2.3.2
        KERAS_PACKAGE: keras==2.3.1
        PYTORCH_PACKAGE: torch==1.6.0+cu101
        TORCHVISION_PACKAGE: torchvision==0.4.1+cu101
        MXNET_PACKAGE: mxnet-cu101==1.7.0.post1
  test-gpu-openmpi-gloo-py3_6-tf2_4_1-keras2_4_3-torch1_7_1-mxnet1_7_0_p1-pyspark_3_0_1:
    extends: test-gpu-base
    build:
      args:
        CUDA_DOCKER_VERSION: 11.0-devel-ubuntu18.04
        TENSORFLOW_PACKAGE: tensorflow-gpu==2.4.1
        KERAS_PACKAGE: keras==2.4.3
        PYTORCH_PACKAGE: torch==1.7.1+cu110
        TORCHVISION_PACKAGE: torchvision==0.4.1+cu110
        MXNET_PACKAGE: mxnet-cu110==1.7.0.post1
  test-gpu-gloo-py3_6-tfhead-keras2_4_3-torchhead-mxnethead-pyspark_3_0_1:
    extends: test-gpu-base
    build:
      args:
        CUDA_DOCKER_VERSION: 11.0-devel-ubuntu18.04
        TENSORFLOW_PACKAGE: tf-nightly-gpu
        KERAS_PACKAGE: keras==2.4.3
        PYTORCH_PACKAGE: torch-nightly
        TORCHVISION_PACKAGE: torchvision
        MXNET_PACKAGE: mxnet-nightly-cu110

  test-mixed-openmpi-gloo-py3_6-tf2_4_1-keras2_4_3-torch1_7_1-mxnet1_7_0_p1-pyspark_3_0_1:
    extends: test-gpu-base
    build:
      args:
        CUDA_DOCKER_VERSION: 11.0-devel-ubuntu18.04
        TENSORFLOW_PACKAGE: tensorflow-gpu==2.4.1
        KERAS_PACKAGE: keras==2.4.3
        PYTORCH_PACKAGE: torch==1.7.1+cu110
        TORCHVISION_PACKAGE: torchvision==0.4.1+cu110
        MXNET_PACKAGE: mxnet-cu110==1.7.0.post1
        HOROVOD_BUILD_FLAGS: ""
        HOROVOD_MIXED_INSTALL: 1
